spring:
  mvc:  # 스프링 MVC 설정
    pathmatch:  # 패스 매칭 설정
      matching-strategy: ant_path_matcher  # 패스 매칭 전략을 ant_path_matcher로 설정
  datasource:
    url: jdbc:mysql://localhost:3306/museum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  # 데이터베이스 URL
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10 # 최대 커넥션 풀 크기
    driver-class-name: com.mysql.cj.jdbc.Driver  # 드라이버 클래스명
  jpa:
    generate-ddl: true  # DDL을 자동 생성하는 설정
    hibernate:
      ddl-auto: update  # 애플리케이션 시작할 때마다 (create) or (update) or (create-drop) or (validate) 하라는 의미
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false  # JDBC 메타데이터를 사용하는 설정
        jdbc:
          lob:
            non_contextual_creation: true  # LOB을 사용하는 설정
    show-sql: true  # 콘솔창에 쿼리를 보여주는 설정
    open-in-view: false  # 영속성 컨텍스트를 자동으로 열어두는 기능을 끄는 설정


